### ISSUE TITLE
Error Color

### ISSUE THREAD

**Issue by infeace** [wesbos/dotfiles#11]
Hello.

How to change my errors to look like yours ?

![myError](https://user-images.githubusercontent.com/42641979/55361023-a210e580-54de-11e9-81b0-59665636f68a.png)

![wesError](https://user-images.githubusercontent.com/42641979/55361028-a6d59980-54de-11e9-9b08-2825e7bd3dc0.png)

Best regards, Max :).

**Comment by wesbos** [comment]
This is ESLint - refer to eslint-config-wesbos for this :)
