### ISSUE TITLE
Request: VSCode CSS

### ISSUE THREAD

**Issue by stephencweiss** [wesbos/dotfiles#14]
Hi Wes! Would you be willing to share the VSCode CSS file that's referenced in your vscode settings? Specifically struggling to figure out the customizations around _what_ gets italicized and what doesn't.

Thanks!

**Comment by wesbos** [comment]
hey - I don't use the custom CSS any longer. The italics are part of my Cobalt2 theme, and the fancy italics are part of the operator mono font. So that combo will get you what I have :)

**Comment by stephencweiss** [comment]
Ha - was just coming back to say I found this issue which resolves it: https://github.com/wesbos/cobalt2-vscode/issues/116

... though I wish I understood how all of the scopes worked - that's on me to figure out.

Thanks!
