### ISSUE TITLE
How do I get set-up with your ESLint globally?

### ISSUE THREAD

**Issue by mblode** [wesbos/dotfiles#7]
I'm trying to set-up my .eslintrc globally to match your dotfiles, however, I'm running into an issue with VSCode where it says: `Cannot find module 'eslint-config-prettier/react' Referenced from: /Users/matthewblode/.eslintrc`. Thank you for your help and I'm loving the Sick Fits tutorial! #BigPoop

**Comment by IvaTsu** [comment]
Did you install that module globally as well? e.g. `npm install --global eslint-config-prettier eslint-plugin-react` ?

**Comment by wesbos** [comment]
I now use eslint-config-wesbos - there is a video on installing it on youtube :)
