### ISSUE TITLE
Missing vs code custom css style from dot file

### ISSUE THREAD

**Issue by sunil-bagde** [wesbos/dotfiles#9]
Hello sir,
If you dont  mind can you share you custom css file as well just for reference .

Thank you

**Comment by mohitsinghs** [comment]
@im-sunil You are looking for [this](https://github.com/wesbos/cobalt2-vscode/blob/master/cobalt2-custom-hacks.css) I guess.

**Comment by wesbos** [comment]
This is part of the vs code theme. Though I don't use it anymore :)

**Comment by anthonybrown** [comment]
so you don't use the `"/Volumes/Macintosh HD/Users/wesbos/.vscodestyles.css"` file?
